### ISSUE TITLE
处理失败！ TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by This-is-XiaoDeng** [This-is-XiaoDeng/XDbot2#89]
### 描述

在使用签到时提示

```text
处理失败！
TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'
```

日志中具体报错为

```text

03-21 19:16:47 [ERROR] plugins | Traceback (most recent call last):
  File "/home/xdisrbq/XDbot2/src/plugins/Core/plugins/sign.py", line 24, in sign_handler
    origin_data = user.get_user_data(qq)
  File "/home/xdisrbq/XDbot2/src/plugins/Core/plugins/etm/user.py", line 12, in get_user_data
    return json.load(open("data/etm/users.json"), encoding="utf-8")[user_id]
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'
```

经测试 cave-a 也出现了该问题

### 重现步骤

/sign

### 截图

![图片](https://user-images.githubusercontent.com/104149371/226592870-cc49a619-8893-4253-bb19-ec888489d59e.png)

**Comment by montmorillonite-CN** [comment]
encoding="utf-8"加到json.load里了（（（（（
